CREATE TABLE MESSAGE (
   NUM        INT NOT NULL,
   SEND_ID    CHAR(20) NOT NULL,
   RV_ID      CHAR(20) NOT NULL,
   SUBJECT    CHAR(200) NOT NULL,
   CONTENT    TEXT NOT NULL,
   REGIST_DAY CHAR(20),
   PRIMARY KEY ( NUM )
);